### ISSUE TITLE
Grocy Addon

### ISSUE THREAD

**Issue by XtremeCoder007** [BelgianNoise/colruyt-products-scraper#9]
Hi,

It would be very nice to incorporate the scraped data into Grocy.

This would populate most if not all major products into Grocy's DB with current pricing.

Future plan i want to do is have an "a.i." generate a shopping list based on promo's which would yield the most profit.

Any interest ?

Thanks,
XtremeCoder007

**Comment by BelgianNoise** [comment]
Hey, thanks for checking out my repos :)

Currently this is not something I am interested in in doing myself.

The data however is (for now) all publicly available in the GCP bucket listed in the README file.
This data will stay public as long as no one tries to milk it.

Something to keep into account with Colruyt is that their prices might differ from location to location.
